name: Create a new patch release
on: workflow_dispatch
jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # - uses: pocket-apps/action-update-version@v1
      #   with:
      #     files: 'package.json, app.yaml'
      #     version-regexp: '\d+.\d+.\d+'
      - name: Create new patch release
        run: .github/scripts/release.py
        env:
          GITHUB_TOKEN: ${{ secrets.TWINE_PASSWORD}}

          
